#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HackAtHomeClient.Resource", IsApplication=true)]

namespace HackAtHomeClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::HackAtHome.CustomAdapters.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::HackAtHome.CustomAdapters.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
			global::HackAtHome.Entities.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::HackAtHome.Entities.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
			global::HackAtHome.SAL.Resource.Animation.slide_in_right = global::HackAtHomeClient.Resource.Animation.slide_in_right;
			global::HackAtHome.SAL.Resource.Animation.slide_out_left = global::HackAtHomeClient.Resource.Animation.slide_out_left;
			global::HackAtHome.SAL.Resource.Drawable.ic_arrow_back = global::HackAtHomeClient.Resource.Drawable.ic_arrow_back;
			global::HackAtHome.SAL.Resource.Id.webview = global::HackAtHomeClient.Resource.Id.webview;
			global::HackAtHome.SAL.Resource.Layout.activity_webview = global::HackAtHomeClient.Resource.Layout.activity_webview;
			global::HackAtHome.SAL.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::HackAtHome.SAL.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
			global::HackAtHome.SAL.Resource.String.title_activity_webview = global::HackAtHomeClient.Resource.String.title_activity_webview;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int AllCaps = 2131099648;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070013
			public const int btnValidate = 2131165203;
			
			// aapt resource value: 0x7f070006
			public const int imgEvidenceImage = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout1 = 2131165191;
			
			// aapt resource value: 0x7f070010
			public const int linearLayout2 = 2131165200;
			
			// aapt resource value: 0x7f07000a
			public const int lstEvidences = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int lytLinearLista = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int txtEmail = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int txtEmailValue = 2131165199;
			
			// aapt resource value: 0x7f070004
			public const int txtEvidenceDescripcion = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int txtEvidenceFullName = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int txtEvidenceStatus = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int txtEvidenceTitle = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int txtEvidences = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int txtFullName = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int txtLabStatus = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int txtLabTitle = 2131165196;
			
			// aapt resource value: 0x7f070011
			public const int txtPassword = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int txtPasswordValue = 2131165202;
			
			// aapt resource value: 0x7f070005
			public const int webDescription = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int webview = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EvidenceDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Evidences = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EvidencesItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int Description = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int Email = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int Evidence = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int Password = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Validate = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int title_activity_webview = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
